import type { Metadata } from "next";
import "./globals.css";
import { Manrope } from "next/font/google";

const manrope = Manrope({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    // Origin Trial tokens
    "origin-trial": [
      process.env.NEXT_PUBLIC_ORIGIN_TRIAL_ONE,
      process.env.NEXT_PUBLIC_ORIGIN_TRIAL_TWO,
      process.env.NEXT_PUBLIC_ORIGIN_TRIAL_THREE,
    ].join(", "),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.className} antialiased`}>{children}</body>
    </html>
  );
}
